fix(rust): Need real find for earthly rust lib, plus handle saving test/coverage build artifacts on failure.

diff --git a/earthly/rust/Earthfile b/earthly/rust/Earthfile
--- a/earthly/rust/Earthfile
+++ b/earthly/rust/Earthfile
@@ -42,7 +42,8 @@ rust-base:
             colordiff \
             graphviz \
             fontconfig \
-            ttf-liberation
+            ttf-liberation \
+            findutils
 
     # Fix up font cache
     RUN fc-cache -f
@@ -88,6 +89,11 @@ rust-base-plus-tools:
 #   - output: Regex matching output artifacts files to be copied to ./target folder in the caller filesystem (image layers).
 #     Use this argument when you want to SAVE an ARTIFACT from the target folder (mounted cache), always trying to minimize the total size of the copied fileset.
 #     For example --output="release/[^\./]+" would keep all the files in /target/release that don't have any extension.
+#   - junit: Filename to save the junit.xml file LOCALLY.
+#            Also saves the junit.xml file in the target layer.
+#            If not defined, "junit.xml" will not be saved, and will not be in the layer.
+#   - coverage: Filename to save the coverage-report.info as LOCALLY
+#            If not defined, "coverage-report.info" will not be saved, but will be in the layer.
 #
 # This is heavily based off of the rust `CARGO` command in the Earthly library.
 # Updates to that library must be reflected in this function when updating the version of the earthly rust library.
@@ -96,17 +102,41 @@ EXECUTE:
     DO rust+CHECK_INITED
     ARG --required cmd
     ARG output
+    ARG junit
+    ARG coverage
     DO rust+SET_CACHE_MOUNTS_ENV
     IF [ "$EARTHLY_KEEP_FINGERPRINTS" = "false" ]
        DO rust+REMOVE_SOURCE_FINGERPRINTS
     END
+
+    # This uses a workaround to TRY/FINALLY not working inside a FUNCTION.
+    # The command is executed and a "fail" file is created ONLY if it fails.
+    # We then check the existance of the "fail" file after any artifacts are saved that
+    # should be saved regardless.
     RUN --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE \
-      set -e; \
-      $cmd; \
-      cargo sweep -r -t $EARTHLY_SWEEP_DAYS; \
-      cargo sweep -r -i;
+        set -e; \
+        rm -f fail; \
+        $cmd || echo fail > fail; \
+        cargo sweep -r -t $EARTHLY_SWEEP_DAYS; \
+        cargo sweep -r -i;
+
+    # We always want to save these (if requested) even if the command fails.
+    IF [ "$junit" != "" ]
+        DO rust+COPY_OUTPUT --output="nextest/ci/junit.xml"
+        SAVE ARTIFACT target/nextest/ci/junit.xml AS LOCAL "$junit"
+    END
+    IF [ "$coverage" != "" ]
+        SAVE ARTIFACT coverage-report.info AS LOCAL "$coverage"
+    END
+
+    # Defer the failure to here.
+    IF [ -f fail ]
+        RUN exit 1
+    END
+
+    # This output is ONLY saved on successful command execution.
     IF [ "$output" != "" ]
-      DO rust+COPY_OUTPUT --output=$output
+        DO rust+COPY_OUTPUT --output=$output
     END
 
 
