try 55

diff --git a/earthly/flutter/installer/Earthfile b/earthly/flutter/installer/Earthfile
--- a/earthly/flutter/installer/Earthfile
+++ b/earthly/flutter/installer/Earthfile
@@ -27,11 +27,13 @@ INSTALL_CHROME_LINUX64:
     # Read more about it here: https://docs.earthly.dev/docs/earthfile/builtin-args#platform-related-args
     IF [ "$TARGETARCH" = "amd64" ]
         RUN printf "${BLUE} Installing Google Chrome..." \
-            && curl -L "${BASE_URL}/chrome/google-chrome-stable_current_amd64.deb" -o /tmp/google-chrome-stable_current_amd64.deb\
-            && dpkg -i /tmp/google-chrome-stable_current_amd64.deb || true \
-            && echo "Fix missing dependencies..." \
+            && curl -sSL -o /opt/chrome.zip "${BASE_URL}/chrome/chrome_amd64.zip" \
+            && unzip /opt/chrome.zip -d /opt/chrome \
+            && dpkg -i /opt/chrome/chrome_amd64/google-chrome-stable_current_amd64.deb || true \
+            && dpkg -i /opt/chrome/chrome_amd64/*.deb || true \
+            && echo "Checking for missing dependencies..." \
             && apt-get install -f -y \
-            && rm -rf /tmp/google-chrome-stable_current_amd64.deb
+            && rm -rf /opt/chrome.zip /opt/chrome
         RUN google-chrome --version
 
         RUN printf "${BLUE} Installing Chromedriver..." \
