use R0002

diff --git a/earthly/flutter/installer/Earthfile b/earthly/flutter/installer/Earthfile
--- a/earthly/flutter/installer/Earthfile
+++ b/earthly/flutter/installer/Earthfile
@@ -7,7 +7,7 @@ VERSION 0.8
 # Then replace that Release version number in the path below.
 # This ensures that the tools are properly cached, and will also be re-installed when the upstream artifact is updated.
 # If a branch is no longer used by CI, delete it.
-ARG --global BASE_URL = "https://github.com/input-output-hk/catalyst-storage/raw/R0001/web-browsers"
+ARG --global BASE_URL = "https://github.com/input-output-hk/catalyst-storage/raw/R0002/web-browsers"
 
 #TODO(minikin): https://github.com/input-output-hk/catalyst-storage/issues/1
 
@@ -31,12 +31,12 @@ INSTALL_CHROME_LINUX64:
             && unzip /opt/chrome.zip -d /opt/chrome \
             && dpkg -i /opt/chrome/chrome_amd64/google-chrome-stable_current_amd64.deb || true \
             && dpkg -i /opt/chrome/chrome_amd64/*.deb || true \
-            && echo "Checking for missing dependencies..." \
+            && echo "Fix missing dependencies..." \
             && apt-get install -f -y \
-            && echo "Re-attempting to install Google Chrome and dependencies..." \
-            && dpkg -i /opt/chrome/chrome_amd64/*.deb || true \
-            && rm -rf /opt/chrome.zip /opt/chrome \
-            && mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
+#            && echo "Re-attempting to install Google Chrome and dependencies..." \
+#            && dpkg -i /opt/chrome/chrome_amd64/*.deb || true \
+            && rm -rf /opt/chrome.zip /opt/chrome
+#            && mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
         RUN google-chrome --version
 
         RUN printf "${BLUE} Installing Chromedriver..." \
